<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\Project;
use Illuminate\Support\Str;

class InstallScriptGenerator
{
    /**
     * @var array<string, mixed>
     */
    protected array $config = [];

    /**
     * Generate install script for a project
     *
     * @param  array<string, mixed>  $options
     */
    public function generate(Project $project, array $options = []): string
    {
        $this->config = array_merge([
            'production' => false,
            'domain' => $options['domain'] ?? $project->domains()->where('is_primary', true)->first()?->domain,
            'email' => $options['email'] ?? config('mail.from.address', 'admin@example.com'),
            'db_driver' => $options['db_driver'] ?? 'pgsql',
            'php_version' => $project->php_version ?? '8.4',
            'node_version' => '22',
            'skip_ssl' => $options['skip_ssl'] ?? false,
            'enable_ufw' => $options['enable_ufw'] ?? true,
            'enable_fail2ban' => $options['enable_fail2ban'] ?? true,
            'enable_redis' => $options['enable_redis'] ?? true,
            'enable_supervisor' => $options['enable_supervisor'] ?? true,
            'queue_workers' => $options['queue_workers'] ?? 2,
            'project_name' => $project->name,
            'project_slug' => $project->slug,
            'repository_url' => $project->repository_url,
            'branch' => $project->branch ?? 'main',
            'framework' => $project->framework ?? 'laravel',
        ], $options);

        return $this->buildScript();
    }

    /**
     * Generate a generic install script with customizable options
     *
     * @param  array<string, mixed>  $options
     */
    public function generateGeneric(array $options): string
    {
        $this->config = array_merge([
            'production' => false,
            'domain' => 'example.com',
            'email' => 'admin@example.com',
            'db_driver' => 'pgsql',
            'db_name' => 'app_database',
            'db_user' => 'app_user',
            'php_version' => '8.4',
            'node_version' => '22',
            'skip_ssl' => false,
            'enable_ufw' => true,
            'enable_fail2ban' => true,
            'enable_redis' => true,
            'enable_supervisor' => true,
            'queue_workers' => 2,
            'project_name' => 'Laravel Application',
            'project_slug' => 'laravel-app',
            'repository_url' => '',
            'branch' => 'main',
            'framework' => 'laravel',
        ], $options);

        return $this->buildScript();
    }

    protected function buildScript(): string
    {
        $script = $this->getHeader();
        $script .= $this->getColors();
        $script .= $this->getConfiguration();
        $script .= $this->getArgumentParser();
        $script .= $this->getHelpFunction();
        $script .= $this->getUtilityFunctions();
        $script .= $this->getSystemUpdates();
        $script .= $this->getPhpInstallation();

        if ($this->config['db_driver'] === 'pgsql') {
            $script .= $this->getPostgresInstallation();
        } else {
            $script .= $this->getMysqlInstallation();
        }

        if ($this->config['enable_redis']) {
            $script .= $this->getRedisInstallation();
        }

        $script .= $this->getNodeInstallation();
        $script .= $this->getComposerInstallation();
        $script .= $this->getNginxInstallation();

        if ($this->config['enable_supervisor']) {
            $script .= $this->getSupervisorInstallation();
        }

        if ($this->config['production']) {
            $script .= $this->getProductionSecuritySetup();
        }

        $script .= $this->getApplicationSetup();
        $script .= $this->getCronSetup();
        $script .= $this->getFinalSummary();

        return $script;
    }

    protected function getHeader(): string
    {
        $projectName = $this->config['project_name'];
        $projectSlug = $this->config['project_slug'];

        return <<<BASH
#!/bin/bash

# =============================================================================
# {$projectName} - Full Installation Script
# Generated by DevFlow Pro - Multi-Project Deployment & Management System
# For Ubuntu/Debian-based systems
#
# Usage:
#   ./install.sh                                              # Development mode
#   ./install.sh --production --domain {$projectSlug}.example.com --email admin@example.com
#
# Options:
#   --production    Enable production mode (security hardening, skip dev tools)
#   --domain        Domain name for SSL certificate (required for production)
#   --email         Email for Let's Encrypt notifications (required for production)
#   --skip-ssl      Skip SSL setup in production (if using external SSL/proxy)
#   --db-driver     Database driver: pgsql or mysql (default: pgsql)
#   --db-password   Set custom database password
#   --help          Show this help message
# =============================================================================

set -e


BASH;
    }

    protected function getColors(): string
    {
        return <<<'BASH'
# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

BASH;
    }

    protected function getConfiguration(): string
    {
        $projectName = $this->config['project_name'];
        $projectSlug = $this->config['project_slug'];
        $dbDriver = $this->config['db_driver'];
        $phpVersion = $this->config['php_version'];
        $nodeVersion = $this->config['node_version'];
        $dbName = $this->config['db_name'] ?? Str::snake($projectSlug);
        $dbUser = $this->config['db_user'] ?? Str::snake($projectSlug);
        $production = $this->config['production'] ? 'true' : 'false';
        $domain = $this->config['domain'] ?? '';
        $email = $this->config['email'] ?? '';

        return <<<BASH
# =============================================================================
# Default Configuration
# =============================================================================
PRODUCTION_MODE={$production}
DOMAIN="{$domain}"
EMAIL="{$email}"
SKIP_SSL=false
DB_DRIVER="{$dbDriver}"
DB_NAME="{$dbName}"
DB_USER="{$dbUser}"
DB_PASSWORD="{$projectSlug}_secret_2024"
DB_TEST_NAME="{$dbName}_test"
PHP_VERSION="{$phpVersion}"
NODE_VERSION="{$nodeVersion}"
PROJECT_NAME="{$projectName}"
PROJECT_SLUG="{$projectSlug}"

# Get script directory (project root)
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

BASH;
    }

    protected function getArgumentParser(): string
    {
        return <<<'BASH'
# =============================================================================
# Parse command line arguments
# =============================================================================
while [[ $# -gt 0 ]]; do
    case $1 in
        --production)
            PRODUCTION_MODE=true
            shift
            ;;
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --skip-ssl)
            SKIP_SSL=true
            shift
            ;;
        --db-driver)
            DB_DRIVER="$2"
            shift 2
            ;;
        --db-password)
            DB_PASSWORD="$2"
            shift 2
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help to see available options"
            exit 1
            ;;
    esac
done

BASH;
    }

    protected function getHelpFunction(): string
    {
        $projectName = $this->config['project_name'];
        $projectSlug = $this->config['project_slug'];

        return <<<BASH
# =============================================================================
# Help function
# =============================================================================
show_help() {
    echo ""
    echo -e "\${CYAN}╔═══════════════════════════════════════════════════════════════╗\${NC}"
    echo -e "\${CYAN}║              {$projectName} - Installation Script              ║\${NC}"
    echo -e "\${CYAN}║             Generated by DevFlow Pro                          ║\${NC}"
    echo -e "\${CYAN}╚═══════════════════════════════════════════════════════════════╝\${NC}"
    echo ""
    echo "Usage: ./install.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --production          Enable production mode with security hardening"
    echo "  --domain DOMAIN       Domain for SSL certificate (required for production)"
    echo "  --email EMAIL         Email for Let's Encrypt notifications"
    echo "  --skip-ssl            Skip SSL setup (use when behind proxy)"
    echo "  --db-driver DRIVER    Database: pgsql (default) or mysql"
    echo "  --db-password PASS    Custom database password"
    echo "  --help, -h            Show this help message"
    echo ""
    echo "Examples:"
    echo -e "  \${GREEN}Development:\${NC}"
    echo "    ./install.sh"
    echo ""
    echo -e "  \${GREEN}Production:\${NC}"
    echo "    ./install.sh --production --domain {$projectSlug}.example.com --email admin@example.com"
    echo ""
    echo -e "  \${GREEN}Production with MySQL:\${NC}"
    echo "    ./install.sh --production --domain {$projectSlug}.example.com --email admin@example.com --db-driver mysql"
    echo ""
}

BASH;
    }

    protected function getUtilityFunctions(): string
    {
        return <<<'BASH'
# =============================================================================
# Utility functions
# =============================================================================
print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

print_step() {
    echo -e "${GREEN}▶${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# =============================================================================
# Validate production requirements
# =============================================================================
if [ "$PRODUCTION_MODE" = true ]; then
    print_header "Production Mode Enabled"

    if [ -z "$DOMAIN" ]; then
        print_error "Domain is required for production mode"
        echo "Usage: ./install.sh --production --domain your-domain.com --email admin@your-domain.com"
        exit 1
    fi

    if [ -z "$EMAIL" ]; then
        print_error "Email is required for production mode (for SSL certificates)"
        echo "Usage: ./install.sh --production --domain your-domain.com --email admin@your-domain.com"
        exit 1
    fi

    # Generate secure password for production
    if [ "$DB_PASSWORD" = "${PROJECT_SLUG}_secret_2024" ]; then
        DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
        print_warning "Generated secure database password"
    fi

    echo -e "  Domain:    ${GREEN}$DOMAIN${NC}"
    echo -e "  Email:     ${GREEN}$EMAIL${NC}"
    echo -e "  Database:  ${GREEN}$DB_DRIVER${NC}"
    echo ""

    read -p "Proceed with production installation? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
else
    print_header "Development Mode"
    echo -e "  Database:  ${GREEN}$DB_DRIVER${NC}"
    echo ""
fi

BASH;
    }

    protected function getSystemUpdates(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 1: System Updates
# =============================================================================
print_header "Step 1: System Updates"

print_step "Updating package lists..."
sudo apt-get update -qq

print_step "Upgrading installed packages..."
sudo apt-get upgrade -y -qq

print_step "Installing essential tools..."
sudo apt-get install -y -qq \
    curl \
    wget \
    git \
    unzip \
    zip \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release

print_success "System updated successfully"

BASH;
    }

    protected function getPhpInstallation(): string
    {
        $phpVersion = $this->config['php_version'];

        return <<<BASH
# =============================================================================
# Step 2: PHP {$phpVersion} Installation
# =============================================================================
print_header "Step 2: PHP {$phpVersion} Installation"

print_step "Adding PHP repository..."
sudo add-apt-repository -y ppa:ondrej/php

print_step "Updating package lists..."
sudo apt-get update -qq

print_step "Installing PHP {$phpVersion} and extensions..."
sudo apt-get install -y -qq \\
    php{$phpVersion}-fpm \\
    php{$phpVersion}-cli \\
    php{$phpVersion}-common \\
    php{$phpVersion}-mbstring \\
    php{$phpVersion}-xml \\
    php{$phpVersion}-zip \\
    php{$phpVersion}-curl \\
    php{$phpVersion}-gd \\
    php{$phpVersion}-intl \\
    php{$phpVersion}-bcmath \\
    php{$phpVersion}-pgsql \\
    php{$phpVersion}-mysql \\
    php{$phpVersion}-sqlite3 \\
    php{$phpVersion}-redis \\
    php{$phpVersion}-opcache \\
    php{$phpVersion}-imagick \\
    php{$phpVersion}-soap \\
    php{$phpVersion}-ldap

print_success "PHP {$phpVersion} installed successfully"

BASH;
    }

    protected function getPostgresInstallation(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 3: PostgreSQL 16 Installation
# =============================================================================
print_header "Step 3: PostgreSQL 16 Installation"

print_step "Adding PostgreSQL repository..."
curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg 2>/dev/null || true
echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

print_step "Installing PostgreSQL 16..."
sudo apt-get update -qq
sudo apt-get install -y -qq postgresql-16 postgresql-contrib-16

print_step "Starting PostgreSQL service..."
sudo systemctl start postgresql
sudo systemctl enable postgresql

print_step "Creating database and user..."
sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || \
    sudo -u postgres psql -c "ALTER USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE $DB_TEST_NAME OWNER $DB_USER;" 2>/dev/null || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_TEST_NAME TO $DB_USER;"

print_success "PostgreSQL 16 installed and configured"

BASH;
    }

    protected function getMysqlInstallation(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 3: MySQL 8 Installation
# =============================================================================
print_header "Step 3: MySQL 8 Installation"

print_step "Installing MySQL 8..."
sudo apt-get install -y -qq mysql-server mysql-client

print_step "Starting MySQL service..."
sudo systemctl start mysql
sudo systemctl enable mysql

print_step "Creating database and user..."
sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_TEST_NAME;"
sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_TEST_NAME.* TO '$DB_USER'@'localhost';"
sudo mysql -e "FLUSH PRIVILEGES;"

print_success "MySQL 8 installed and configured"

BASH;
    }

    protected function getRedisInstallation(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 4: Redis Installation
# =============================================================================
print_header "Step 4: Redis Installation"

print_step "Installing Redis..."
sudo apt-get install -y -qq redis-server

print_step "Configuring Redis..."
sudo sed -i 's/^supervised no/supervised systemd/' /etc/redis/redis.conf

print_step "Starting Redis service..."
sudo systemctl start redis
sudo systemctl enable redis

print_success "Redis installed successfully"

BASH;
    }

    protected function getNodeInstallation(): string
    {
        $nodeVersion = $this->config['node_version'];

        return <<<BASH
# =============================================================================
# Step 5: Node.js {$nodeVersion} Installation
# =============================================================================
print_header "Step 5: Node.js {$nodeVersion} Installation"

if command_exists node; then
    print_warning "Node.js is already installed"
else
    print_step "Installing Node.js {$nodeVersion}..."
    curl -fsSL https://deb.nodesource.com/setup_{$nodeVersion}.x | sudo -E bash -
    sudo apt-get install -y -qq nodejs
fi

print_success "Node.js installed: \$(node -v)"

BASH;
    }

    protected function getComposerInstallation(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 6: Composer Installation
# =============================================================================
print_header "Step 6: Composer Installation"

if command_exists composer; then
    print_warning "Composer is already installed"
else
    print_step "Installing Composer..."
    curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/local/bin/composer
    sudo chmod +x /usr/local/bin/composer
fi

print_success "Composer installed: $(composer --version 2>/dev/null | head -1)"

BASH;
    }

    protected function getNginxInstallation(): string
    {
        $phpVersion = $this->config['php_version'];
        $projectSlug = $this->config['project_slug'];

        return <<<BASH
# =============================================================================
# Step 7: Nginx Installation
# =============================================================================
print_header "Step 7: Nginx Installation"

print_step "Installing Nginx..."
sudo apt-get install -y -qq nginx

print_step "Creating Nginx configuration..."
NGINX_CONF="/etc/nginx/sites-available/{$projectSlug}"

if [ "\$PRODUCTION_MODE" = true ]; then
    SERVER_NAME="\$DOMAIN"
else
    SERVER_NAME="localhost {$projectSlug}.test"
fi

sudo tee \$NGINX_CONF > /dev/null <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name \$SERVER_NAME;
    root \$SCRIPT_DIR/public;

    index index.php index.html;

    charset utf-8;
    client_max_body_size 100M;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files \\\$uri \\\$uri/ /index.php?\\\$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \\.php\$ {
        fastcgi_pass unix:/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \\\$realpath_root\\\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;
}
NGINX

print_step "Enabling site..."
sudo ln -sf \$NGINX_CONF /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default

print_step "Testing Nginx configuration..."
sudo nginx -t

print_step "Restarting Nginx..."
sudo systemctl restart nginx
sudo systemctl enable nginx

print_success "Nginx installed and configured"

BASH;
    }

    protected function getSupervisorInstallation(): string
    {
        $projectSlug = $this->config['project_slug'];
        $queueWorkers = $this->config['queue_workers'];

        return <<<BASH
# =============================================================================
# Step 8: Supervisor Installation (Queue Workers)
# =============================================================================
print_header "Step 8: Supervisor Installation"

print_step "Installing Supervisor..."
sudo apt-get install -y -qq supervisor

print_step "Creating queue worker configuration..."
sudo tee /etc/supervisor/conf.d/{$projectSlug}-worker.conf > /dev/null <<EOF
[program:{$projectSlug}-worker]
process_name=%(program_name)s_%(process_num)02d
command=php \$SCRIPT_DIR/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs={$queueWorkers}
redirect_stderr=true
stdout_logfile=\$SCRIPT_DIR/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stopwaitsecs=3600
EOF

print_step "Restarting Supervisor..."
sudo supervisorctl reread
sudo supervisorctl update

print_success "Supervisor installed and configured"

BASH;
    }

    protected function getProductionSecuritySetup(): string
    {
        $phpVersion = $this->config['php_version'];

        return <<<BASH
# =============================================================================
# Step 9: Production Security Hardening
# =============================================================================
print_header "Step 9: Production Security Hardening"

# --- UFW Firewall ---
print_step "Configuring UFW Firewall..."
sudo apt-get install -y -qq ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
echo "y" | sudo ufw enable
print_success "UFW Firewall configured"

# --- Fail2ban ---
print_step "Installing and configuring Fail2ban..."
sudo apt-get install -y -qq fail2ban

sudo tee /etc/fail2ban/jail.local > /dev/null <<EOF
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 24h

[nginx-http-auth]
enabled = true

[nginx-botsearch]
enabled = true

[nginx-bad-request]
enabled = true
EOF

sudo systemctl restart fail2ban
sudo systemctl enable fail2ban
print_success "Fail2ban configured"

# --- SSL Certificate ---
if [ "\$SKIP_SSL" = false ]; then
    print_step "Installing Certbot for SSL..."
    sudo apt-get install -y -qq certbot python3-certbot-nginx

    print_step "Obtaining SSL certificate..."
    sudo certbot --nginx -d \$DOMAIN --non-interactive --agree-tos --email \$EMAIL --redirect || {
        print_warning "SSL certificate setup failed. You may need to configure DNS first."
    }
fi

# --- PHP Production Optimizations ---
print_step "Applying PHP production optimizations..."
sudo tee /etc/php/{$phpVersion}/fpm/conf.d/99-production.ini > /dev/null <<EOF
; Production Optimizations - Generated by DevFlow Pro
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=50000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.save_comments=1
opcache.enable_cli=0

; JIT for PHP 8.0+
opcache.jit=1255
opcache.jit_buffer_size=128M

; Security
expose_php=Off
display_errors=Off
log_errors=On
error_log=/var/log/php-errors.log
EOF

sudo systemctl restart php{$phpVersion}-fpm
print_success "PHP production optimizations applied"

# --- Secure File Permissions ---
print_step "Setting secure file permissions..."
sudo chown -R www-data:www-data \$SCRIPT_DIR
sudo find \$SCRIPT_DIR -type f -exec chmod 644 {} \\;
sudo find \$SCRIPT_DIR -type d -exec chmod 755 {} \\;
sudo chmod -R 775 \$SCRIPT_DIR/storage \$SCRIPT_DIR/bootstrap/cache
if [ -f "\$SCRIPT_DIR/.env" ]; then
    sudo chmod 640 \$SCRIPT_DIR/.env
fi
print_success "Secure file permissions set"

BASH;
    }

    protected function getApplicationSetup(): string
    {
        $dbDriver = $this->config['db_driver'];
        $dbConnection = $dbDriver === 'pgsql' ? 'pgsql' : 'mysql';

        return <<<BASH
# =============================================================================
# Step 10: Application Setup
# =============================================================================
print_header "Step 10: Application Setup"

cd "\$SCRIPT_DIR"

print_step "Installing PHP dependencies..."
if [ "\$PRODUCTION_MODE" = true ]; then
    composer install --no-dev --optimize-autoloader --no-interaction
else
    composer install --no-interaction
fi

print_step "Installing NPM dependencies..."
npm install

print_step "Building frontend assets..."
npm run build

print_step "Setting up environment file..."
if [ ! -f .env ]; then
    cp .env.example .env
fi

# Update database configuration
sed -i "s/^DB_CONNECTION=.*/DB_CONNECTION={$dbConnection}/" .env
sed -i "s/^DB_DATABASE=.*/DB_DATABASE=\$DB_NAME/" .env
sed -i "s/^DB_USERNAME=.*/DB_USERNAME=\$DB_USER/" .env
sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=\$DB_PASSWORD/" .env

if [ "\$PRODUCTION_MODE" = true ]; then
    sed -i "s/^APP_ENV=.*/APP_ENV=production/" .env
    sed -i "s/^APP_DEBUG=.*/APP_DEBUG=false/" .env
    sed -i "s|^APP_URL=.*|APP_URL=https://\$DOMAIN|" .env
fi

print_step "Generating application key..."
php artisan key:generate --force

print_step "Running database migrations..."
php artisan migrate --force

print_step "Creating storage link..."
php artisan storage:link

if [ "\$PRODUCTION_MODE" = true ]; then
    print_step "Caching configuration..."
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    php artisan event:cache
fi

print_success "Application setup complete"

BASH;
    }

    protected function getCronSetup(): string
    {
        return <<<'BASH'
# =============================================================================
# Step 11: Cron Job Setup
# =============================================================================
print_header "Step 11: Cron Job Setup"

print_step "Setting up Laravel scheduler..."
CRON_JOB="* * * * * cd $SCRIPT_DIR && php artisan schedule:run >> /dev/null 2>&1"

# Check if cron job already exists
(crontab -l 2>/dev/null | grep -v "artisan schedule:run"; echo "$CRON_JOB") | crontab -

print_success "Cron job configured"

BASH;
    }

    protected function getFinalSummary(): string
    {
        $projectName = $this->config['project_name'];

        return <<<BASH
# =============================================================================
# Installation Complete
# =============================================================================
print_header "Installation Complete!"

echo ""
echo -e "\${GREEN}╔═══════════════════════════════════════════════════════════════╗\${NC}"
echo -e "\${GREEN}║              {$projectName} - Ready!                           ║\${NC}"
echo -e "\${GREEN}╚═══════════════════════════════════════════════════════════════╝\${NC}"
echo ""

if [ "\$PRODUCTION_MODE" = true ]; then
    echo -e "\${CYAN}Production Environment:\${NC}"
    echo -e "  URL:        \${GREEN}https://\$DOMAIN\${NC}"
    echo -e "  Database:   \${GREEN}\$DB_DRIVER\${NC}"
    echo -e "  DB Name:    \${GREEN}\$DB_NAME\${NC}"
    echo -e "  DB User:    \${GREEN}\$DB_USER\${NC}"
    echo -e "  DB Pass:    \${YELLOW}\$DB_PASSWORD\${NC}"
    echo ""
    echo -e "\${CYAN}Security Features Enabled:\${NC}"
    echo -e "  ✓ UFW Firewall (ports 22, 80, 443)"
    echo -e "  ✓ Fail2ban brute-force protection"
    if [ "\$SKIP_SSL" = false ]; then
        echo -e "  ✓ Let's Encrypt SSL certificate"
    fi
    echo -e "  ✓ PHP OPcache + JIT optimizations"
    echo -e "  ✓ Secure file permissions"
else
    echo -e "\${CYAN}Development Environment:\${NC}"
    echo -e "  URL:        \${GREEN}http://localhost\${NC}"
    echo -e "  Database:   \${GREEN}\$DB_DRIVER\${NC}"
    echo -e "  DB Name:    \${GREEN}\$DB_NAME\${NC}"
    echo -e "  DB User:    \${GREEN}\$DB_USER\${NC}"
    echo -e "  DB Pass:    \${GREEN}\$DB_PASSWORD\${NC}"
fi

echo ""
echo -e "\${CYAN}Next Steps:\${NC}"
echo -e "  1. Update your .env file with remaining configuration"
echo -e "  2. Create an admin user: php artisan tinker"
echo -e "  3. Run tests: php artisan test"
echo ""
echo -e "\${MAGENTA}Generated by DevFlow Pro - Multi-Project Deployment System\${NC}"
echo ""

BASH;
    }
}
