<?php

declare(strict_types=1);

namespace Tests\Feature\Integration;


use PHPUnit\Framework\Attributes\Test;
use App\Models\Project;
use App\Models\Server;
use App\Models\Team;
use App\Models\TeamInvitation;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

/**
 * Team Collaboration Integration Test
 *
 * This test suite covers the complete team collaboration workflow,
 * including team creation, member invitations, permissions, and shared resources.
 *
 * Workflows covered:
 * 1. Team creation and setup
 * 2. Member invitation flow (send, accept, reject)
 * 3. Role-based permissions
 * 4. Shared resource access (projects, servers)
 * 5. Team switching and current team context
 * 6. Team deletion and member cleanup
 */
class TeamCollaborationTest extends TestCase
{
    use RefreshDatabase;

    protected User $owner;

    protected Team $team;

    protected function setUp(): void
    {
        parent::setUp();

        Notification::fake();

        $this->owner = User::factory()->create([
            'email' => 'owner@devflow.com',
            'name' => 'Team Owner',
        ]);

        $this->team = Team::factory()->create([
            'name' => 'DevFlow Team',
            'owner_id' => $this->owner->id,
        ]);

        // Attach owner to team
        $this->team->members()->attach($this->owner->id, ['role' => 'owner']);
    }

    // ==================== Team Creation Tests ====================

    #[Test]
    public function user_can_create_team(): void
    {
        $user = User::factory()->create();

        $team = Team::factory()->create([
            'name' => 'New Team',
            'owner_id' => $user->id,
        ]);

        $this->assertDatabaseHas('teams', [
            'name' => 'New Team',
            'owner_id' => $user->id,
        ]);
    }

    #[Test]
    public function team_owner_is_automatically_added_as_member(): void
    {
        $this->assertTrue($this->team->hasMember($this->owner));
        $this->assertEquals('owner', $this->team->getMemberRole($this->owner));
    }

    #[Test]
    public function user_can_have_multiple_teams(): void
    {
        $team2 = Team::factory()->create([
            'name' => 'Second Team',
            'owner_id' => $this->owner->id,
        ]);
        $team2->members()->attach($this->owner->id, ['role' => 'owner']);

        $team3 = Team::factory()->create([
            'name' => 'Third Team',
            'owner_id' => $this->owner->id,
        ]);
        $team3->members()->attach($this->owner->id, ['role' => 'owner']);

        $ownerTeams = $this->owner->teams;
        $this->assertCount(3, $ownerTeams);
    }

    // ==================== Member Invitation Tests ====================

    #[Test]
    public function owner_can_invite_member_to_team(): void
    {
        $invitation = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'newmember@example.com',
            'role' => 'member',
            'invited_by' => $this->owner->id,
        ]);

        $this->assertDatabaseHas('team_invitations', [
            'team_id' => $this->team->id,
            'email' => 'newmember@example.com',
            'role' => 'member',
        ]);
    }

    #[Test]
    public function invitation_generates_unique_token(): void
    {
        $invitation1 = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'user1@example.com',
        ]);

        $invitation2 = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'user2@example.com',
        ]);

        // Tokens are generated by factory - verify they exist and are different
        $this->assertNotEmpty($invitation1->token);
        $this->assertNotEmpty($invitation2->token);
        $this->assertNotEquals($invitation1->token, $invitation2->token);
    }

    #[Test]
    public function user_can_accept_invitation(): void
    {
        $newUser = User::factory()->create([
            'email' => 'newmember@example.com',
        ]);

        $invitation = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => $newUser->email,
            'role' => 'member',
        ]);

        // Simulate accepting invitation
        $this->team->members()->attach($newUser->id, ['role' => $invitation->role]);
        $invitationId = $invitation->id;
        $invitation->delete();

        $freshTeam = $this->team->fresh();
        $this->assertNotNull($freshTeam);
        $this->assertTrue($freshTeam->hasMember($newUser));
        $this->assertDatabaseMissing('team_invitations', ['id' => $invitationId]);
    }

    #[Test]
    public function invitation_can_be_canceled(): void
    {
        $invitation = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'pending@example.com',
        ]);

        $invitationId = $invitation->id;
        $invitation->delete();

        $this->assertDatabaseMissing('team_invitations', ['id' => $invitationId]);
    }

    #[Test]
    public function invitation_expires_after_period(): void
    {
        $invitation = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'expired@example.com',
            'expires_at' => now()->subDays(1),
        ]);

        $expiredInvitations = TeamInvitation::where('expires_at', '<', now())->get();

        $this->assertCount(1, $expiredInvitations);
    }

    // ==================== Role & Permission Tests ====================

    #[Test]
    public function team_supports_multiple_roles(): void
    {
        $admin = User::factory()->create();
        $member = User::factory()->create();
        $viewer = User::factory()->create();

        $this->team->members()->attach($admin->id, ['role' => 'admin']);
        $this->team->members()->attach($member->id, ['role' => 'member']);
        $this->team->members()->attach($viewer->id, ['role' => 'viewer']);

        $this->assertEquals('admin', $this->team->getMemberRole($admin));
        $this->assertEquals('member', $this->team->getMemberRole($member));
        $this->assertEquals('viewer', $this->team->getMemberRole($viewer));
    }

    #[Test]
    public function owner_can_change_member_role(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        // Promote to admin
        $this->team->members()->updateExistingPivot($member->id, ['role' => 'admin']);

        $freshTeam = $this->team->fresh();
        $this->assertNotNull($freshTeam);
        $this->assertEquals('admin', $freshTeam->getMemberRole($member));
    }

    #[Test]
    public function owner_cannot_change_own_role(): void
    {
        // Owner's role should remain 'owner'
        $this->assertEquals('owner', $this->team->getMemberRole($this->owner));

        // Even if we try to update it, the owner role should be protected
        // This would be enforced by business logic, not the database
    }

    #[Test]
    public function admin_can_invite_members(): void
    {
        $admin = User::factory()->create();
        $this->team->members()->attach($admin->id, ['role' => 'admin']);

        // Admin creates invitation
        $invitation = TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'invited-by-admin@example.com',
            'invited_by' => $admin->id,
            'role' => 'member',
        ]);

        $this->assertEquals($admin->id, $invitation->invited_by);
    }

    // ==================== Shared Resource Tests ====================

    #[Test]
    public function team_members_can_access_team_projects(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        $server = Server::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
        ]);

        $project = Project::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
            'server_id' => $server->id,
        ]);

        // Team project should be accessible to member
        $teamProjects = Project::where('team_id', $this->team->id)->get();

        $this->assertCount(1, $teamProjects);
        $firstProject = $teamProjects->first();
        $this->assertNotNull($firstProject);
        $this->assertEquals($project->id, $firstProject->id);
    }

    #[Test]
    public function team_members_can_access_team_servers(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        Server::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
            'name' => 'Team Server',
        ]);

        $teamServers = Server::where('team_id', $this->team->id)->get();

        $this->assertCount(1, $teamServers);
    }

    #[Test]
    public function personal_projects_not_visible_to_team(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        // Owner's personal project (no team)
        $personalServer = Server::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => null,
        ]);

        Project::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => null,
            'server_id' => $personalServer->id,
            'name' => 'Personal Project',
        ]);

        $teamProjects = Project::where('team_id', $this->team->id)->get();

        $this->assertCount(0, $teamProjects);
    }

    // ==================== Team Switching Tests ====================

    #[Test]
    public function user_can_switch_current_team(): void
    {
        $team2 = Team::factory()->create([
            'owner_id' => $this->owner->id,
        ]);
        $team2->members()->attach($this->owner->id, ['role' => 'owner']);

        // Set initial current team
        $this->owner->update(['current_team_id' => $this->team->id]);

        $this->assertEquals($this->team->id, $this->owner->current_team_id);

        // Switch to team2
        $this->owner->update(['current_team_id' => $team2->id]);

        $freshOwner = $this->owner->fresh();
        $this->assertNotNull($freshOwner);
        $this->assertEquals($team2->id, $freshOwner->current_team_id);
    }

    #[Test]
    public function current_team_affects_resource_context(): void
    {
        $this->owner->update(['current_team_id' => $this->team->id]);

        $server = Server::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
        ]);

        // Resources created while team is current
        $project = Project::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->owner->current_team_id,
            'server_id' => $server->id,
        ]);

        $this->assertEquals($this->team->id, $project->team_id);
    }

    // ==================== Member Removal Tests ====================

    #[Test]
    public function owner_can_remove_member(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        $this->assertTrue($this->team->hasMember($member));

        // Remove member
        $this->team->members()->detach($member->id);

        $freshTeam = $this->team->fresh();
        $this->assertNotNull($freshTeam);
        $this->assertFalse($freshTeam->hasMember($member));
    }

    #[Test]
    public function member_can_leave_team(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        // Member leaves
        $this->team->members()->detach($member->id);

        $freshTeam = $this->team->fresh();
        $this->assertNotNull($freshTeam);
        $this->assertFalse($freshTeam->hasMember($member));
    }

    #[Test]
    public function owner_cannot_leave_team(): void
    {
        // Owner should not be able to leave without transferring ownership
        $this->assertTrue($this->team->hasMember($this->owner));
        $this->assertTrue($this->team->isOwner($this->owner));

        // Business logic would prevent this, verified by checking owner status
    }

    // ==================== Team Deletion Tests ====================

    #[Test]
    public function deleting_team_removes_member_associations(): void
    {
        $member1 = User::factory()->create();
        $member2 = User::factory()->create();

        $this->team->members()->attach($member1->id, ['role' => 'member']);
        $this->team->members()->attach($member2->id, ['role' => 'member']);

        $teamId = $this->team->id;

        $this->team->delete();

        $this->assertDatabaseMissing('teams', ['id' => $teamId]);
        $this->assertDatabaseMissing('team_user', ['team_id' => $teamId]);
    }

    #[Test]
    public function deleting_team_removes_pending_invitations(): void
    {
        TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'pending1@example.com',
        ]);

        TeamInvitation::factory()->create([
            'team_id' => $this->team->id,
            'email' => 'pending2@example.com',
        ]);

        $teamId = $this->team->id;

        $this->team->delete();

        $this->assertDatabaseMissing('team_invitations', ['team_id' => $teamId]);
    }

    // ==================== Team Statistics Tests ====================

    #[Test]
    public function calculates_team_member_count(): void
    {
        User::factory()->count(5)->create()->each(function ($user) {
            $this->team->members()->attach($user->id, ['role' => 'member']);
        });

        // Owner + 5 members = 6
        $this->assertEquals(6, $this->team->members()->count());
    }

    #[Test]
    public function tracks_team_resource_counts(): void
    {
        $server = Server::factory()->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
        ]);

        Project::factory()->count(3)->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
            'server_id' => $server->id,
        ]);

        Server::factory()->count(2)->create([
            'user_id' => $this->owner->id,
            'team_id' => $this->team->id,
        ]);

        $projectCount = Project::where('team_id', $this->team->id)->count();
        $serverCount = Server::where('team_id', $this->team->id)->count();

        $this->assertEquals(3, $projectCount);
        $this->assertEquals(3, $serverCount); // 1 + 2
    }

    // ==================== Ownership Transfer Tests ====================

    #[Test]
    public function can_transfer_team_ownership(): void
    {
        $newOwner = User::factory()->create();
        $this->team->members()->attach($newOwner->id, ['role' => 'admin']);

        // Transfer ownership
        $this->team->update(['owner_id' => $newOwner->id]);
        $this->team->members()->updateExistingPivot($newOwner->id, ['role' => 'owner']);
        $this->team->members()->updateExistingPivot($this->owner->id, ['role' => 'admin']);

        $freshTeam = $this->team->fresh();
        $this->assertNotNull($freshTeam);
        $this->assertEquals($newOwner->id, $freshTeam->owner_id);
        $this->assertEquals('owner', $freshTeam->getMemberRole($newOwner));
        $this->assertEquals('admin', $freshTeam->getMemberRole($this->owner));
    }

    // ==================== Activity & Audit Tests ====================

    #[Test]
    public function team_activity_is_trackable(): void
    {
        // This would typically use activity logging
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, ['role' => 'member']);

        // Activity would be logged with team context
        $this->assertTrue($this->team->hasMember($member));
    }

    #[Test]
    public function member_changes_are_timestamped(): void
    {
        $member = User::factory()->create();
        $this->team->members()->attach($member->id, [
            'role' => 'member',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $teamMember = $this->team->members()->where('user_id', $member->id)->first();
        $this->assertNotNull($teamMember);
        // Pivot is always present for relationships with pivot data
        $this->assertNotNull($teamMember->pivot->created_at);
    }
}
